# Generated by Django 2.1.7 on 2019-04-08 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(max_length=200)),
                ('tuesday', models.CharField(max_length=200)),
                ('wednesday', models.CharField(max_length=200)),
                ('thursday', models.CharField(max_length=200)),
                ('friday', models.CharField(max_length=200)),
                ('saturday', models.CharField(max_length=200)),
                ('sunday', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=55, max_digits=55)),
                ('longitude', models.DecimalField(decimal_places=55, max_digits=55)),
                ('stars', models.DecimalField(decimal_places=55, max_digits=55)),
                ('review_count', models.IntegerField()),
                ('is_open', models.BooleanField()),
                ('categories', models.CharField(max_length=200)),
                ('hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Hours')),
            ],
        ),
    ]
